# Generated by Django 2.2.2 on 2019-06-26 07:23

from django.db import migrations, models
import info.utils


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190626_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': '该用户名已存在.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[info.utils.CodeUsernameValidator()], verbose_name='username'),
        ),
    ]
