# Generated by Django 2.2.2 on 2019-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190626_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(help_text='用户号码', max_length=11, null=True, unique=True, verbose_name='用户号码'),
        ),
    ]
