# Generated by Django 2.2.2 on 2019-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expired_time',
            field=models.CharField(blank=True, help_text='过期时间', max_length=30, null=True, verbose_name='过期时间'),
        ),
    ]
